### ISSUE TITLE
Implementar Servidor de la APP

### ISSUE THREAD

**Issue by profealejandroduoc** [profealejandroduoc/marioapp#8]
## # Tareas para implementar el Hosting

- [x] Comprar dominio
- [x] Comprar hosting
- [ ] Vincular dominio al hosting

**Comment by profealejandroduoc** [comment]
Falta vincular al hosting

**Comment by Ju4nc0** [comment]
esta listo

**Comment by profealejandroduoc** [comment]
Listo para continuar
